services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              device_ids:
                - '0'
              driver: nvidia
    environment:
      - CLI_ARGS=
    image: yanwk/comfyui-boot:cu130-slim
    init: true
    ports:
      - '8188:8188'
    security_opt:
      - label=type:nvidia_container_t
    volumes:
      - "./storage:/root"
      - "./storage-models/models:/root/ComfyUI/models"
      - "./storage-models/hf-hub:/root/.cache/huggingface/hub"
      - "./storage-models/torch-hub:/root/.cache/torch/hub"
      - "./storage-user/input:/root/ComfyUI/input"
      - "./storage-user/output:/root/ComfyUI/output"
      - "./storage-user/workflows:/root/ComfyUI/user/default/workflows"
